when:
  branch: [master]
  event: [push, pull_request]

matrix:
  OS:
    - ubuntu-plucky
    - ubuntu-noble
    - ubuntu-xenial
    - fedora-42
    - fedora-41
    - fedora-39

variables:
  - &buildenv 'alexanderamelkin/frugen-buildenv:${OS}'

clone:
  - name: git
    image: woodpeckerci/plugin-git
    settings:
      tags: true

steps:
  build-all:
    image: *buildenv
    # Pull the image on the first step only
    pull: true
    commands: >
      # Run the build.

      mkdir build

      cd build

      cmake ..

      make

  build-static:
    image: *buildenv
    commands: >
      # Run the build.

      rm -rf build

      mkdir build

      cd build

      cmake -DBINARY_STATIC=true -DBUILD_SHARED_LIB=false ..

      make

  build-semistatic:
    image: *buildenv
    commands: >
      # Run the build.

      rm -rf build

      mkdir build

      cd build

      cmake -DJSON_STATIC=true -DBUILD_SHARED_LIB=false ..

      make

  docs:
    image: *buildenv
    commands: >
      # Run the build.

      rm -rf build

      mkdir build

      cd build

      cmake ..

      make docs
